name: Phobos Bugfix Request
description: Open an issue to ask for a phobos bug to be fixed.
title: "Your bug report title here"
body:
  - type: markdown
    attributes:
      value: |
        - [ ] check
        - [x] uncheck
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
